pokemon(bulbasaur).
pokemon(ivysaur).
pokemon(venusaur).
pokemon(charmander).
pokemon(charmeleon).
pokemon(charizard).
pokemon(squirtle).
pokemon(wartortle).
pokemon(blastoise).
pokemon(caterpie).
pokemon(metapod).
pokemon(butterfree).
pokemon(weedle).
pokemon(kakuna).
pokemon(beedrill).
pokemon(pidgey).
pokemon(pidgeotto).
pokemon(pidgeot).
pokemon(rattata).
pokemon(raticate).
pokemon(spearow).
pokemon(fearow).
pokemon(ekans).
pokemon(arbok).
pokemon(pikachu).
pokemon(raichu).
pokemon(sandshrew).
pokemon(sandslash).
pokemon(nidoran-f).
pokemon(nidorina).
pokemon(nidoqueen).
pokemon(nidoran-m).
pokemon(nidorino).
pokemon(nidoking).
pokemon(clefairy).
pokemon(clefable).
pokemon(vulpix).
pokemon(ninetales).
pokemon(jigglypuff).
pokemon(wigglytuff).
pokemon(zubat).
pokemon(golbat).
pokemon(oddish).
pokemon(gloom).
pokemon(vileplume).
pokemon(paras).
pokemon(parasect).
pokemon(venonat).
pokemon(venomoth).
pokemon(diglett).
pokemon(dugtrio).
pokemon(meowth).
pokemon(persian).
pokemon(psyduck).
pokemon(golduck).
pokemon(mankey).
pokemon(primeape).
pokemon(growlithe).
pokemon(arcanine).
pokemon(poliwag).
pokemon(poliwhirl).
pokemon(poliwrath).
pokemon(abra).
pokemon(kadabra).
pokemon(alakazam).
pokemon(machop).
pokemon(machoke).
pokemon(machamp).
pokemon(bellsprout).
pokemon(weepinbell).
pokemon(victreebel).
pokemon(tentacool).
pokemon(tentacruel).
pokemon(geodude).
pokemon(graveler).
pokemon(golem).
pokemon(ponyta).
pokemon(rapidash).
pokemon(slowpoke).
pokemon(slowbro).
pokemon(magnemite).
pokemon(magneton).
pokemon(farfetchd).
pokemon(doduo).
pokemon(dodrio).
pokemon(seel).
pokemon(dewgong).
pokemon(grimer).
pokemon(muk).
pokemon(shellder).
pokemon(cloyster).
pokemon(gastly).
pokemon(haunter).
pokemon(gengar).
pokemon(onix).
pokemon(drowzee).
pokemon(hypno).
pokemon(krabby).
pokemon(kingler).
pokemon(voltorb).
pokemon(electrode).
pokemon(exeggcute).
pokemon(exeggutor).
pokemon(cubone).
pokemon(marowak).
pokemon(hitmonlee).
pokemon(hitmonchan).
pokemon(lickitung).
pokemon(koffing).
pokemon(weezing).
pokemon(rhyhorn).
pokemon(rhydon).
pokemon(chansey).
pokemon(tangela).
pokemon(kangaskhan).
pokemon(horsea).
pokemon(seadra).
pokemon(goldeen).
pokemon(seaking).
pokemon(staryu).
pokemon(starmie).
pokemon(mr-mime).
pokemon(scyther).
pokemon(jynx).
pokemon(electabuzz).
pokemon(magmar).
pokemon(pinsir).
pokemon(tauros).
pokemon(magikarp).
pokemon(gyarados).
pokemon(lapras).
pokemon(ditto).
pokemon(eevee).
pokemon(vaporeon).
pokemon(jolteon).
pokemon(flareon).
pokemon(porygon).
pokemon(omanyte).
pokemon(omastar).
pokemon(kabuto).
pokemon(kabutops).
pokemon(aerodactyl).
pokemon(snorlax).
pokemon(articuno).
pokemon(zapdos).
pokemon(moltres).
pokemon(dratini).
pokemon(dragonair).
pokemon(dragonite).
pokemon(mewtwo).
pokemon(mew).
pokemon(chikorita).
pokemon(bayleef).
pokemon(meganium).
pokemon(cyndaquil).
pokemon(quilava).
pokemon(typhlosion).
pokemon(totodile).
pokemon(croconaw).
pokemon(feraligatr).
pokemon(sentret).
pokemon(furret).
pokemon(hoothoot).
pokemon(noctowl).
pokemon(ledyba).
pokemon(ledian).
pokemon(spinarak).
pokemon(ariados).
pokemon(crobat).
pokemon(chinchou).
pokemon(lanturn).
pokemon(pichu).
pokemon(cleffa).
pokemon(igglybuff).
pokemon(togepi).
pokemon(togetic).
pokemon(natu).
pokemon(xatu).
pokemon(mareep).
pokemon(flaaffy).
pokemon(ampharos).
pokemon(bellossom).
pokemon(marill).
pokemon(azumarill).
pokemon(sudowoodo).
pokemon(politoed).
pokemon(hoppip).
pokemon(skiploom).
pokemon(jumpluff).
pokemon(aipom).
pokemon(sunkern).
pokemon(sunflora).
pokemon(yanma).
pokemon(wooper).
pokemon(quagsire).
pokemon(espeon).
pokemon(umbreon).
pokemon(murkrow).
pokemon(slowking).
pokemon(misdreavus).
pokemon(unown-a).
pokemon(wobbuffet).
pokemon(girafarig).
pokemon(pineco).
pokemon(forretress).
pokemon(dunsparce).
pokemon(gligar).
pokemon(steelix).
pokemon(snubbull).
pokemon(granbull).
pokemon(qwilfish).
pokemon(scizor).
pokemon(shuckle).
pokemon(heracross).
pokemon(sneasel).
pokemon(teddiursa).
pokemon(ursaring).
pokemon(slugma).
pokemon(magcargo).
pokemon(swinub).
pokemon(piloswine).
pokemon(corsola).
pokemon(remoraid).
pokemon(octillery).
pokemon(delibird).
pokemon(mantine).
pokemon(skarmory).
pokemon(houndour).
pokemon(houndoom).
pokemon(kingdra).
pokemon(phanpy).
pokemon(donphan).
pokemon(porygon2).
pokemon(stantler).
pokemon(smeargle).
pokemon(tyrogue).
pokemon(hitmontop).
pokemon(smoochum).
pokemon(elekid).
pokemon(magby).
pokemon(miltank).
pokemon(blissey).
pokemon(raikou).
pokemon(entei).
pokemon(suicune).
pokemon(larvitar).
pokemon(pupitar).
pokemon(tyranitar).
pokemon(lugia).
pokemon(ho-oh).
pokemon(celebi).
pokemon(treecko).
pokemon(grovyle).
pokemon(sceptile).
pokemon(torchic).
pokemon(combusken).
pokemon(blaziken).
pokemon(mudkip).
pokemon(marshtomp).
pokemon(swampert).
pokemon(poochyena).
pokemon(mightyena).
pokemon(zigzagoon).
pokemon(linoone).
pokemon(wurmple).
pokemon(silcoon).
pokemon(beautifly).
pokemon(cascoon).
pokemon(dustox).
pokemon(lotad).
pokemon(lombre).
pokemon(ludicolo).
pokemon(seedot).
pokemon(nuzleaf).
pokemon(shiftry).
pokemon(taillow).
pokemon(swellow).
pokemon(wingull).
pokemon(pelipper).
pokemon(ralts).
pokemon(kirlia).
pokemon(gardevoir).
pokemon(surskit).
pokemon(masquerain).
pokemon(shroomish).
pokemon(breloom).
pokemon(slakoth).
pokemon(vigoroth).
pokemon(slaking).
pokemon(nincada).
pokemon(ninjask).
pokemon(shedinja).
pokemon(whismur).
pokemon(loudred).
pokemon(exploud).
pokemon(makuhita).
pokemon(hariyama).
pokemon(azurill).
pokemon(nosepass).
pokemon(skitty).
pokemon(delcatty).
pokemon(sableye).
pokemon(mawile).
pokemon(aron).
pokemon(lairon).
pokemon(aggron).
pokemon(meditite).
pokemon(medicham).
pokemon(electrike).
pokemon(manectric).
pokemon(plusle).
pokemon(minun).
pokemon(volbeat).
pokemon(illumise).
pokemon(roselia).
pokemon(gulpin).
pokemon(swalot).
pokemon(carvanha).
pokemon(sharpedo).
pokemon(wailmer).
pokemon(wailord).
pokemon(numel).
pokemon(camerupt).
pokemon(torkoal).
pokemon(spoink).
pokemon(grumpig).
pokemon(spinda).
pokemon(trapinch).
pokemon(vibrava).
pokemon(flygon).
pokemon(cacnea).
pokemon(cacturne).
pokemon(swablu).
pokemon(altaria).
pokemon(zangoose).
pokemon(seviper).
pokemon(lunatone).
pokemon(solrock).
pokemon(barboach).
pokemon(whiscash).
pokemon(corphish).
pokemon(crawdaunt).
pokemon(baltoy).
pokemon(claydol).
pokemon(lileep).
pokemon(cradily).
pokemon(anorith).
pokemon(armaldo).
pokemon(feebas).
pokemon(milotic).
pokemon(castform).
pokemon(kecleon).
pokemon(shuppet).
pokemon(banette).
pokemon(duskull).
pokemon(dusclops).
pokemon(tropius).
pokemon(chimecho).
pokemon(absol).
pokemon(wynaut).
pokemon(snorunt).
pokemon(glalie).
pokemon(spheal).
pokemon(sealeo).
pokemon(walrein).
pokemon(clamperl).
pokemon(huntail).
pokemon(gorebyss).
pokemon(relicanth).
pokemon(luvdisc).
pokemon(bagon).
pokemon(shelgon).
pokemon(salamence).
pokemon(beldum).
pokemon(metang).
pokemon(metagross).
pokemon(regirock).
pokemon(regice).
pokemon(registeel).
pokemon(latias).
pokemon(latios).
pokemon(kyogre).
pokemon(groudon).
pokemon(rayquaza).
pokemon(jirachi).
have_type(bulbasaur,grass).
have_type(bulbasaur,poison).
have_type(ivysaur,grass).
have_type(ivysaur,poison).
have_type(venusaur,grass).
have_type(venusaur,poison).
have_type(charmander,fire).
have_type(charmeleon,fire).
have_type(charizard,fire).
have_type(charizard,flying).
have_type(squirtle,water).
have_type(wartortle,water).
have_type(blastoise,water).
have_type(caterpie,bug).
have_type(metapod,bug).
have_type(butterfree,bug).
have_type(butterfree,flying).
have_type(weedle,bug).
have_type(weedle,poison).
have_type(kakuna,bug).
have_type(kakuna,poison).
have_type(beedrill,bug).
have_type(beedrill,poison).
have_type(pidgey,normal).
have_type(pidgey,flying).
have_type(pidgeotto,normal).
have_type(pidgeotto,flying).
have_type(pidgeot,normal).
have_type(pidgeot,flying).
have_type(rattata,normal).
have_type(raticate,normal).
have_type(spearow,normal).
have_type(spearow,flying).
have_type(fearow,normal).
have_type(fearow,flying).
have_type(ekans,poison).
have_type(arbok,poison).
have_type(pikachu,electric).
have_type(raichu,electric).
have_type(sandshrew,ground).
have_type(sandslash,ground).
have_type(nidoran-f,poison).
have_type(nidorina,poison).
have_type(nidoqueen,poison).
have_type(nidoqueen,ground).
have_type(nidoran-m,poison).
have_type(nidorino,poison).
have_type(nidoking,poison).
have_type(nidoking,ground).
have_type(clefairy,fairy).
have_type(clefable,fairy).
have_type(vulpix,fire).
have_type(ninetales,fire).
have_type(jigglypuff,normal).
have_type(jigglypuff,fairy).
have_type(wigglytuff,normal).
have_type(wigglytuff,fairy).
have_type(zubat,poison).
have_type(zubat,flying).
have_type(golbat,poison).
have_type(golbat,flying).
have_type(oddish,grass).
have_type(oddish,poison).
have_type(gloom,grass).
have_type(gloom,poison).
have_type(vileplume,grass).
have_type(vileplume,poison).
have_type(paras,bug).
have_type(paras,grass).
have_type(parasect,bug).
have_type(parasect,grass).
have_type(venonat,bug).
have_type(venonat,poison).
have_type(venomoth,bug).
have_type(venomoth,poison).
have_type(diglett,ground).
have_type(dugtrio,ground).
have_type(meowth,normal).
have_type(persian,normal).
have_type(psyduck,water).
have_type(golduck,water).
have_type(mankey,fighting).
have_type(primeape,fighting).
have_type(growlithe,fire).
have_type(arcanine,fire).
have_type(poliwag,water).
have_type(poliwhirl,water).
have_type(poliwrath,water).
have_type(poliwrath,fighting).
have_type(abra,psychic).
have_type(kadabra,psychic).
have_type(alakazam,psychic).
have_type(machop,fighting).
have_type(machoke,fighting).
have_type(machamp,fighting).
have_type(bellsprout,grass).
have_type(bellsprout,poison).
have_type(weepinbell,grass).
have_type(weepinbell,poison).
have_type(victreebel,grass).
have_type(victreebel,poison).
have_type(tentacool,water).
have_type(tentacool,poison).
have_type(tentacruel,water).
have_type(tentacruel,poison).
have_type(geodude,rock).
have_type(geodude,ground).
have_type(graveler,rock).
have_type(graveler,ground).
have_type(golem,rock).
have_type(golem,ground).
have_type(ponyta,fire).
have_type(rapidash,fire).
have_type(slowpoke,water).
have_type(slowpoke,psychic).
have_type(slowbro,water).
have_type(slowbro,psychic).
have_type(magnemite,electric).
have_type(magnemite,steel).
have_type(magneton,electric).
have_type(magneton,steel).
have_type(farfetchd,normal).
have_type(farfetchd,flying).
have_type(doduo,normal).
have_type(doduo,flying).
have_type(dodrio,normal).
have_type(dodrio,flying).
have_type(seel,water).
have_type(dewgong,water).
have_type(dewgong,ice).
have_type(grimer,poison).
have_type(muk,poison).
have_type(shellder,water).
have_type(cloyster,water).
have_type(cloyster,ice).
have_type(gastly,ghost).
have_type(gastly,poison).
have_type(haunter,ghost).
have_type(haunter,poison).
have_type(gengar,ghost).
have_type(gengar,poison).
have_type(onix,rock).
have_type(onix,ground).
have_type(drowzee,psychic).
have_type(hypno,psychic).
have_type(krabby,water).
have_type(kingler,water).
have_type(voltorb,electric).
have_type(electrode,electric).
have_type(exeggcute,grass).
have_type(exeggcute,psychic).
have_type(exeggutor,grass).
have_type(exeggutor,psychic).
have_type(cubone,ground).
have_type(marowak,ground).
have_type(hitmonlee,fighting).
have_type(hitmonchan,fighting).
have_type(lickitung,normal).
have_type(koffing,poison).
have_type(weezing,poison).
have_type(rhyhorn,ground).
have_type(rhyhorn,rock).
have_type(rhydon,ground).
have_type(rhydon,rock).
have_type(chansey,normal).
have_type(tangela,grass).
have_type(kangaskhan,normal).
have_type(horsea,water).
have_type(seadra,water).
have_type(goldeen,water).
have_type(seaking,water).
have_type(staryu,water).
have_type(starmie,water).
have_type(starmie,psychic).
have_type(mr-mime,psychic).
have_type(mr-mime,fairy).
have_type(scyther,bug).
have_type(scyther,flying).
have_type(jynx,ice).
have_type(jynx,psychic).
have_type(electabuzz,electric).
have_type(magmar,fire).
have_type(pinsir,bug).
have_type(tauros,normal).
have_type(magikarp,water).
have_type(gyarados,water).
have_type(gyarados,flying).
have_type(lapras,water).
have_type(lapras,ice).
have_type(ditto,normal).
have_type(eevee,normal).
have_type(vaporeon,water).
have_type(jolteon,electric).
have_type(flareon,fire).
have_type(porygon,normal).
have_type(omanyte,rock).
have_type(omanyte,water).
have_type(omastar,rock).
have_type(omastar,water).
have_type(kabuto,rock).
have_type(kabuto,water).
have_type(kabutops,rock).
have_type(kabutops,water).
have_type(aerodactyl,rock).
have_type(aerodactyl,flying).
have_type(snorlax,normal).
have_type(articuno,ice).
have_type(articuno,flying).
have_type(zapdos,electric).
have_type(zapdos,flying).
have_type(moltres,fire).
have_type(moltres,flying).
have_type(dratini,dragon).
have_type(dragonair,dragon).
have_type(dragonite,dragon).
have_type(dragonite,flying).
have_type(mewtwo,psychic).
have_type(mew,psychic).
have_type(chikorita,grass).
have_type(bayleef,grass).
have_type(meganium,grass).
have_type(cyndaquil,fire).
have_type(quilava,fire).
have_type(typhlosion,fire).
have_type(totodile,water).
have_type(croconaw,water).
have_type(feraligatr,water).
have_type(sentret,normal).
have_type(furret,normal).
have_type(hoothoot,normal).
have_type(hoothoot,flying).
have_type(noctowl,normal).
have_type(noctowl,flying).
have_type(ledyba,bug).
have_type(ledyba,flying).
have_type(ledian,bug).
have_type(ledian,flying).
have_type(spinarak,bug).
have_type(spinarak,poison).
have_type(ariados,bug).
have_type(ariados,poison).
have_type(crobat,poison).
have_type(crobat,flying).
have_type(chinchou,water).
have_type(chinchou,electric).
have_type(lanturn,water).
have_type(lanturn,electric).
have_type(pichu,electric).
have_type(cleffa,fairy).
have_type(igglybuff,normal).
have_type(igglybuff,fairy).
have_type(togepi,fairy).
have_type(togetic,fairy).
have_type(togetic,flying).
have_type(natu,psychic).
have_type(natu,flying).
have_type(xatu,psychic).
have_type(xatu,flying).
have_type(mareep,electric).
have_type(flaaffy,electric).
have_type(ampharos,electric).
have_type(bellossom,grass).
have_type(marill,water).
have_type(marill,fairy).
have_type(azumarill,water).
have_type(azumarill,fairy).
have_type(sudowoodo,rock).
have_type(politoed,water).
have_type(hoppip,grass).
have_type(hoppip,flying).
have_type(skiploom,grass).
have_type(skiploom,flying).
have_type(jumpluff,grass).
have_type(jumpluff,flying).
have_type(aipom,normal).
have_type(sunkern,grass).
have_type(sunflora,grass).
have_type(yanma,bug).
have_type(yanma,flying).
have_type(wooper,water).
have_type(wooper,ground).
have_type(quagsire,water).
have_type(quagsire,ground).
have_type(espeon,psychic).
have_type(umbreon,dark).
have_type(murkrow,dark).
have_type(murkrow,flying).
have_type(slowking,water).
have_type(slowking,psychic).
have_type(misdreavus,ghost).
have_type(unown-a,psychic).
have_type(wobbuffet,psychic).
have_type(girafarig,normal).
have_type(girafarig,psychic).
have_type(pineco,bug).
have_type(forretress,bug).
have_type(forretress,steel).
have_type(dunsparce,normal).
have_type(gligar,ground).
have_type(gligar,flying).
have_type(steelix,steel).
have_type(steelix,ground).
have_type(snubbull,fairy).
have_type(granbull,fairy).
have_type(qwilfish,water).
have_type(qwilfish,poison).
have_type(scizor,bug).
have_type(scizor,steel).
have_type(shuckle,bug).
have_type(shuckle,rock).
have_type(heracross,bug).
have_type(heracross,fighting).
have_type(sneasel,dark).
have_type(sneasel,ice).
have_type(teddiursa,normal).
have_type(ursaring,normal).
have_type(slugma,fire).
have_type(magcargo,fire).
have_type(magcargo,rock).
have_type(swinub,ice).
have_type(swinub,ground).
have_type(piloswine,ice).
have_type(piloswine,ground).
have_type(corsola,water).
have_type(corsola,rock).
have_type(remoraid,water).
have_type(octillery,water).
have_type(delibird,ice).
have_type(delibird,flying).
have_type(mantine,water).
have_type(mantine,flying).
have_type(skarmory,steel).
have_type(skarmory,flying).
have_type(houndour,dark).
have_type(houndour,fire).
have_type(houndoom,dark).
have_type(houndoom,fire).
have_type(kingdra,water).
have_type(kingdra,dragon).
have_type(phanpy,ground).
have_type(donphan,ground).
have_type(porygon2,normal).
have_type(stantler,normal).
have_type(smeargle,normal).
have_type(tyrogue,fighting).
have_type(hitmontop,fighting).
have_type(smoochum,ice).
have_type(smoochum,psychic).
have_type(elekid,electric).
have_type(magby,fire).
have_type(miltank,normal).
have_type(blissey,normal).
have_type(raikou,electric).
have_type(entei,fire).
have_type(suicune,water).
have_type(larvitar,rock).
have_type(larvitar,ground).
have_type(pupitar,rock).
have_type(pupitar,ground).
have_type(tyranitar,rock).
have_type(tyranitar,dark).
have_type(lugia,psychic).
have_type(lugia,flying).
have_type(ho-oh,fire).
have_type(ho-oh,flying).
have_type(celebi,psychic).
have_type(celebi,grass).
have_type(treecko,grass).
have_type(grovyle,grass).
have_type(sceptile,grass).
have_type(torchic,fire).
have_type(combusken,fire).
have_type(combusken,fighting).
have_type(blaziken,fire).
have_type(blaziken,fighting).
have_type(mudkip,water).
have_type(marshtomp,water).
have_type(marshtomp,ground).
have_type(swampert,water).
have_type(swampert,ground).
have_type(poochyena,dark).
have_type(mightyena,dark).
have_type(zigzagoon,normal).
have_type(linoone,normal).
have_type(wurmple,bug).
have_type(silcoon,bug).
have_type(beautifly,bug).
have_type(beautifly,flying).
have_type(cascoon,bug).
have_type(dustox,bug).
have_type(dustox,poison).
have_type(lotad,water).
have_type(lotad,grass).
have_type(lombre,water).
have_type(lombre,grass).
have_type(ludicolo,water).
have_type(ludicolo,grass).
have_type(seedot,grass).
have_type(nuzleaf,grass).
have_type(nuzleaf,dark).
have_type(shiftry,grass).
have_type(shiftry,dark).
have_type(taillow,normal).
have_type(taillow,flying).
have_type(swellow,normal).
have_type(swellow,flying).
have_type(wingull,water).
have_type(wingull,flying).
have_type(pelipper,water).
have_type(pelipper,flying).
have_type(ralts,psychic).
have_type(ralts,fairy).
have_type(kirlia,psychic).
have_type(kirlia,fairy).
have_type(gardevoir,psychic).
have_type(gardevoir,fairy).
have_type(surskit,bug).
have_type(surskit,water).
have_type(masquerain,bug).
have_type(masquerain,flying).
have_type(shroomish,grass).
have_type(breloom,grass).
have_type(breloom,fighting).
have_type(slakoth,normal).
have_type(vigoroth,normal).
have_type(slaking,normal).
have_type(nincada,bug).
have_type(nincada,ground).
have_type(ninjask,bug).
have_type(ninjask,flying).
have_type(shedinja,bug).
have_type(shedinja,ghost).
have_type(whismur,normal).
have_type(loudred,normal).
have_type(exploud,normal).
have_type(makuhita,fighting).
have_type(hariyama,fighting).
have_type(azurill,normal).
have_type(azurill,fairy).
have_type(nosepass,rock).
have_type(skitty,normal).
have_type(delcatty,normal).
have_type(sableye,dark).
have_type(sableye,ghost).
have_type(mawile,steel).
have_type(mawile,fairy).
have_type(aron,steel).
have_type(aron,rock).
have_type(lairon,steel).
have_type(lairon,rock).
have_type(aggron,steel).
have_type(aggron,rock).
have_type(meditite,fighting).
have_type(meditite,psychic).
have_type(medicham,fighting).
have_type(medicham,psychic).
have_type(electrike,electric).
have_type(manectric,electric).
have_type(plusle,electric).
have_type(minun,electric).
have_type(volbeat,bug).
have_type(illumise,bug).
have_type(roselia,grass).
have_type(roselia,poison).
have_type(gulpin,poison).
have_type(swalot,poison).
have_type(carvanha,water).
have_type(carvanha,dark).
have_type(sharpedo,water).
have_type(sharpedo,dark).
have_type(wailmer,water).
have_type(wailord,water).
have_type(numel,fire).
have_type(numel,ground).
have_type(camerupt,fire).
have_type(camerupt,ground).
have_type(torkoal,fire).
have_type(spoink,psychic).
have_type(grumpig,psychic).
have_type(spinda,normal).
have_type(trapinch,ground).
have_type(vibrava,ground).
have_type(vibrava,dragon).
have_type(flygon,ground).
have_type(flygon,dragon).
have_type(cacnea,grass).
have_type(cacturne,grass).
have_type(cacturne,dark).
have_type(swablu,normal).
have_type(swablu,flying).
have_type(altaria,dragon).
have_type(altaria,flying).
have_type(zangoose,normal).
have_type(seviper,poison).
have_type(lunatone,rock).
have_type(lunatone,psychic).
have_type(solrock,rock).
have_type(solrock,psychic).
have_type(barboach,water).
have_type(barboach,ground).
have_type(whiscash,water).
have_type(whiscash,ground).
have_type(corphish,water).
have_type(crawdaunt,water).
have_type(crawdaunt,dark).
have_type(baltoy,ground).
have_type(baltoy,psychic).
have_type(claydol,ground).
have_type(claydol,psychic).
have_type(lileep,rock).
have_type(lileep,grass).
have_type(cradily,rock).
have_type(cradily,grass).
have_type(anorith,rock).
have_type(anorith,bug).
have_type(armaldo,rock).
have_type(armaldo,bug).
have_type(feebas,water).
have_type(milotic,water).
have_type(castform,normal).
have_type(kecleon,normal).
have_type(shuppet,ghost).
have_type(banette,ghost).
have_type(duskull,ghost).
have_type(dusclops,ghost).
have_type(tropius,grass).
have_type(tropius,flying).
have_type(chimecho,psychic).
have_type(absol,dark).
have_type(wynaut,psychic).
have_type(snorunt,ice).
have_type(glalie,ice).
have_type(spheal,ice).
have_type(spheal,water).
have_type(sealeo,ice).
have_type(sealeo,water).
have_type(walrein,ice).
have_type(walrein,water).
have_type(clamperl,water).
have_type(huntail,water).
have_type(gorebyss,water).
have_type(relicanth,water).
have_type(relicanth,rock).
have_type(luvdisc,water).
have_type(bagon,dragon).
have_type(shelgon,dragon).
have_type(salamence,dragon).
have_type(salamence,flying).
have_type(beldum,steel).
have_type(beldum,psychic).
have_type(metang,steel).
have_type(metang,psychic).
have_type(metagross,steel).
have_type(metagross,psychic).
have_type(regirock,rock).
have_type(regice,ice).
have_type(registeel,steel).
have_type(latias,dragon).
have_type(latias,psychic).
have_type(latios,dragon).
have_type(latios,psychic).
have_type(kyogre,water).
have_type(groudon,ground).
have_type(rayquaza,dragon).
have_type(rayquaza,flying).
have_type(jirachi,steel).
have_type(jirachi,psychic).
type(normal).
type(fighting).
type(flying).
type(poison).
type(ground).
type(rock).
type(bug).
type(ghost).
type(steel).
type(fire).
type(water).
type(grass).
type(electric).
type(psychic).
type(ice).
type(dragon).
type(dark).
type(fairy).
effective(normal,rock,0.5).
effective(normal,steel,0.5).
effective(normal,ghost,0).
effective(normal,normal,1).
effective(normal,fighting,1).
effective(normal,flying,1).
effective(normal,poison,1).
effective(normal,ground,1).
effective(normal,bug,1).
effective(normal,fire,1).
effective(normal,water,1).
effective(normal,grass,1).
effective(normal,electric,1).
effective(normal,psychic,1).
effective(normal,ice,1).
effective(normal,dragon,1).
effective(normal,dark,1).
effective(normal,fairy,1).
effective(fighting,flying,0.5).
effective(fighting,poison,0.5).
effective(fighting,bug,0.5).
effective(fighting,psychic,0.5).
effective(fighting,fairy,0.5).
effective(fighting,normal,2).
effective(fighting,rock,2).
effective(fighting,steel,2).
effective(fighting,ice,2).
effective(fighting,dark,2).
effective(fighting,ghost,0).
effective(fighting,fighting,1).
effective(fighting,ground,1).
effective(fighting,fire,1).
effective(fighting,water,1).
effective(fighting,grass,1).
effective(fighting,electric,1).
effective(fighting,dragon,1).
effective(flying,rock,0.5).
effective(flying,steel,0.5).
effective(flying,electric,0.5).
effective(flying,fighting,2).
effective(flying,bug,2).
effective(flying,grass,2).
effective(flying,normal,1).
effective(flying,flying,1).
effective(flying,poison,1).
effective(flying,ground,1).
effective(flying,ghost,1).
effective(flying,fire,1).
effective(flying,water,1).
effective(flying,psychic,1).
effective(flying,ice,1).
effective(flying,dragon,1).
effective(flying,dark,1).
effective(flying,fairy,1).
effective(poison,poison,0.5).
effective(poison,ground,0.5).
effective(poison,rock,0.5).
effective(poison,ghost,0.5).
effective(poison,grass,2).
effective(poison,fairy,2).
effective(poison,steel,0).
effective(poison,normal,1).
effective(poison,fighting,1).
effective(poison,flying,1).
effective(poison,bug,1).
effective(poison,fire,1).
effective(poison,water,1).
effective(poison,electric,1).
effective(poison,psychic,1).
effective(poison,ice,1).
effective(poison,dragon,1).
effective(poison,dark,1).
effective(ground,bug,0.5).
effective(ground,grass,0.5).
effective(ground,poison,2).
effective(ground,rock,2).
effective(ground,steel,2).
effective(ground,fire,2).
effective(ground,electric,2).
effective(ground,flying,0).
effective(ground,normal,1).
effective(ground,fighting,1).
effective(ground,ground,1).
effective(ground,ghost,1).
effective(ground,water,1).
effective(ground,psychic,1).
effective(ground,ice,1).
effective(ground,dragon,1).
effective(ground,dark,1).
effective(ground,fairy,1).
effective(rock,fighting,0.5).
effective(rock,ground,0.5).
effective(rock,steel,0.5).
effective(rock,flying,2).
effective(rock,bug,2).
effective(rock,fire,2).
effective(rock,ice,2).
effective(rock,normal,1).
effective(rock,poison,1).
effective(rock,rock,1).
effective(rock,ghost,1).
effective(rock,water,1).
effective(rock,grass,1).
effective(rock,electric,1).
effective(rock,psychic,1).
effective(rock,dragon,1).
effective(rock,dark,1).
effective(rock,fairy,1).
effective(bug,fighting,0.5).
effective(bug,flying,0.5).
effective(bug,poison,0.5).
effective(bug,ghost,0.5).
effective(bug,steel,0.5).
effective(bug,fire,0.5).
effective(bug,fairy,0.5).
effective(bug,grass,2).
effective(bug,psychic,2).
effective(bug,dark,2).
effective(bug,normal,1).
effective(bug,ground,1).
effective(bug,rock,1).
effective(bug,bug,1).
effective(bug,water,1).
effective(bug,electric,1).
effective(bug,ice,1).
effective(bug,dragon,1).
effective(ghost,dark,0.5).
effective(ghost,ghost,2).
effective(ghost,psychic,2).
effective(ghost,normal,0).
effective(ghost,fighting,1).
effective(ghost,flying,1).
effective(ghost,poison,1).
effective(ghost,ground,1).
effective(ghost,rock,1).
effective(ghost,bug,1).
effective(ghost,steel,1).
effective(ghost,fire,1).
effective(ghost,water,1).
effective(ghost,grass,1).
effective(ghost,electric,1).
effective(ghost,ice,1).
effective(ghost,dragon,1).
effective(ghost,fairy,1).
effective(steel,steel,0.5).
effective(steel,fire,0.5).
effective(steel,water,0.5).
effective(steel,electric,0.5).
effective(steel,rock,2).
effective(steel,ice,2).
effective(steel,fairy,2).
effective(steel,normal,1).
effective(steel,fighting,1).
effective(steel,flying,1).
effective(steel,poison,1).
effective(steel,ground,1).
effective(steel,bug,1).
effective(steel,ghost,1).
effective(steel,grass,1).
effective(steel,psychic,1).
effective(steel,dragon,1).
effective(steel,dark,1).
effective(fire,rock,0.5).
effective(fire,fire,0.5).
effective(fire,water,0.5).
effective(fire,dragon,0.5).
effective(fire,bug,2).
effective(fire,steel,2).
effective(fire,grass,2).
effective(fire,ice,2).
effective(fire,normal,1).
effective(fire,fighting,1).
effective(fire,flying,1).
effective(fire,poison,1).
effective(fire,ground,1).
effective(fire,ghost,1).
effective(fire,electric,1).
effective(fire,psychic,1).
effective(fire,dark,1).
effective(fire,fairy,1).
effective(water,water,0.5).
effective(water,grass,0.5).
effective(water,dragon,0.5).
effective(water,ground,2).
effective(water,rock,2).
effective(water,fire,2).
effective(water,normal,1).
effective(water,fighting,1).
effective(water,flying,1).
effective(water,poison,1).
effective(water,bug,1).
effective(water,ghost,1).
effective(water,steel,1).
effective(water,electric,1).
effective(water,psychic,1).
effective(water,ice,1).
effective(water,dark,1).
effective(water,fairy,1).
effective(grass,flying,0.5).
effective(grass,poison,0.5).
effective(grass,bug,0.5).
effective(grass,steel,0.5).
effective(grass,fire,0.5).
effective(grass,grass,0.5).
effective(grass,dragon,0.5).
effective(grass,ground,2).
effective(grass,rock,2).
effective(grass,water,2).
effective(grass,normal,1).
effective(grass,fighting,1).
effective(grass,ghost,1).
effective(grass,electric,1).
effective(grass,psychic,1).
effective(grass,ice,1).
effective(grass,dark,1).
effective(grass,fairy,1).
effective(electric,grass,0.5).
effective(electric,electric,0.5).
effective(electric,dragon,0.5).
effective(electric,flying,2).
effective(electric,water,2).
effective(electric,ground,0).
effective(electric,normal,1).
effective(electric,fighting,1).
effective(electric,poison,1).
effective(electric,rock,1).
effective(electric,bug,1).
effective(electric,ghost,1).
effective(electric,steel,1).
effective(electric,fire,1).
effective(electric,psychic,1).
effective(electric,ice,1).
effective(electric,dark,1).
effective(electric,fairy,1).
effective(psychic,steel,0.5).
effective(psychic,psychic,0.5).
effective(psychic,fighting,2).
effective(psychic,poison,2).
effective(psychic,dark,0).
effective(psychic,normal,1).
effective(psychic,flying,1).
effective(psychic,ground,1).
effective(psychic,rock,1).
effective(psychic,bug,1).
effective(psychic,ghost,1).
effective(psychic,fire,1).
effective(psychic,water,1).
effective(psychic,grass,1).
effective(psychic,electric,1).
effective(psychic,ice,1).
effective(psychic,dragon,1).
effective(psychic,fairy,1).
effective(ice,steel,0.5).
effective(ice,fire,0.5).
effective(ice,water,0.5).
effective(ice,ice,0.5).
effective(ice,flying,2).
effective(ice,ground,2).
effective(ice,grass,2).
effective(ice,dragon,2).
effective(ice,normal,1).
effective(ice,fighting,1).
effective(ice,poison,1).
effective(ice,rock,1).
effective(ice,bug,1).
effective(ice,ghost,1).
effective(ice,electric,1).
effective(ice,psychic,1).
effective(ice,dark,1).
effective(ice,fairy,1).
effective(dragon,steel,0.5).
effective(dragon,dragon,2).
effective(dragon,fairy,0).
effective(dragon,normal,1).
effective(dragon,fighting,1).
effective(dragon,flying,1).
effective(dragon,poison,1).
effective(dragon,ground,1).
effective(dragon,rock,1).
effective(dragon,bug,1).
effective(dragon,ghost,1).
effective(dragon,fire,1).
effective(dragon,water,1).
effective(dragon,grass,1).
effective(dragon,electric,1).
effective(dragon,psychic,1).
effective(dragon,ice,1).
effective(dragon,dark,1).
effective(dark,fighting,0.5).
effective(dark,dark,0.5).
effective(dark,fairy,0.5).
effective(dark,ghost,2).
effective(dark,psychic,2).
effective(dark,normal,1).
effective(dark,flying,1).
effective(dark,poison,1).
effective(dark,ground,1).
effective(dark,rock,1).
effective(dark,bug,1).
effective(dark,steel,1).
effective(dark,fire,1).
effective(dark,water,1).
effective(dark,grass,1).
effective(dark,electric,1).
effective(dark,ice,1).
effective(dark,dragon,1).
effective(fairy,poison,0.5).
effective(fairy,steel,0.5).
effective(fairy,fire,0.5).
effective(fairy,fighting,2).
effective(fairy,dragon,2).
effective(fairy,dark,2).
effective(fairy,normal,1).
effective(fairy,flying,1).
effective(fairy,ground,1).
effective(fairy,rock,1).
effective(fairy,bug,1).
effective(fairy,ghost,1).
effective(fairy,water,1).
effective(fairy,grass,1).
effective(fairy,electric,1).
effective(fairy,psychic,1).
effective(fairy,ice,1).
effective(fairy,fairy,1).
